### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by douglasdcm** [jacksonchen1998/Twitter-Crawler#2]
Hi, how are you? Which version of Python are you using?

**Comment by jacksonchen1998** [comment]
Hello @douglasdcm.  If you mean the Twitter crawler. I'm using `3.9.13`

**Comment by douglasdcm** [comment]
No, I mean, I will need to install the Python dependencies via pip, right? So, which version of Python do I need to install to use this repository: 3.6, 3,10,...?
